name=MotorDriver
version=1.0.0
author=Karl Smirthwaite <nqn524@york.ac.uk>
maintainer=Karl Smirthwaite <nqn524@york.ac.uk>
sentence=Driver Motor
paragraph=That's it
category=Control
url=https://github.com/nqn524/WebAppControl
architecture=mbed_nano
includes=MotorDriver.h
depends=mbed.h