name=RobotCompControl
version=1.0.0
author=Karl Smirthwaite <nqn524@york.ac.uk>
maintainer=Karl Smirthwaite <nqn524@york.ac.uk>
sentence=Provides an easy way to connect a joystick 
paragraph=Also can do buttons
category=Communication
url=https://github.com/nqn524/WebAppControl
architecture=mbed_nano
includes=RCControl.h
depends=ArduinoBLE